[package]
name = "main_"
version = "0.1.0"
edition = "2018"

[profile.dev]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
